### PR TITLE
Update recipe for v2.2.5

### PR DESCRIPTION
**Pull request by timj**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by timj** [comment]
@conda-forge-admin, please rerender

**Comment by timj** [comment]
@ktlim I waited a few days but the bot never discovered the new release on GitHub so I decided to make the PR manually.

**Comment by beckermr** [comment]
According to the status page, the bot found the release but encountered an error.

**Comment by timj** [comment]
The bot finally triggered and automerged in #36.

**Pull request closed without merging**
