### PR TITLE
Make (de)activate scripts POSIX.

### PR DESCRIPTION
**Pull request by ktlim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by ktlim** [comment]
osx_arm64 py3.8 failure appears to be due to inability to execute this:
```
"$EUPS_PYTHON" -c "import sys;print(\"EUPS_PYTHON :\ninterpreter : %s\nversion : %s\" % (sys.executable, sys.version))"
```
I'm at a loss.

**Comment by erykoff** [comment]
Building locally, I can replicate the error.  But it only errors with `conda mambabuild` (as in the new rerender) but _not_ with `conda build`.  So this might be some subtle bug in `boa`.  One option would be to add `build_with_mambabuild: false` to the `conda-forge.yml` and rerender and see if that passes.  This is a simple enough solve that it would be fine for the time being.  But it would be nice to figure out what's going on and have a proper bug report upstream.

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by erykoff** [comment]
Hey @isuruf ... the new version of `crossenv=1.1.4` from https://github.com/conda-forge/crossenv-feedstock/pull/22 seems to have broken with python=3.8.  The error (when running locally) is:
```
  File "/Users/erykoff/x86_conda/mambaforge/envs/build39_x86_2/conda-bld/eups_1640635405049/_build_env/lib/python3.8/sysconfig.py", line 439, in _init_posix
    name = _get_sysconfigdata_name(True)
TypeError: _get_sysconfigdata_name() takes 0 positional arguments but 1 was given
```
When I pin `crossenv=1.0` on this feedstock then things work.  (The mambabuild was a red herring, it had to do with cached versions locally and I just got "lucky" that I got the old working crossenv).

**Comment by erykoff** [comment]
@conda-forge-admin please restart ci

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by erykoff** [comment]
CI seems to still be picking up the old build of `crossenv`, though the new one should be available.  We might just need to wait until tomorrow?

**Comment by erykoff** [comment]
...and now it worked!  Hooray!

**Pull request merged**
