### PR TITLE
Make activate/deactivate scripts zsh-compatible.

### PR DESCRIPTION
**Pull request by ktlim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by gcomoretto — APPROVED** [review]

**Review by timj — APPROVED** [review]

**Comment by beckermr** [comment]
You need to rerender prs like this. It is not always required but it is always a good idea.

**Comment by beckermr** [comment]
See the checklist above.

**Comment by ktlim** [comment]
Past changes to the activate/deactivate scripts alone ended up with null rerenders, so I haven't been rerendering since.

**Comment by beckermr** [comment]
As we push changes to conda smithy, they are only propagated via rerendering. So we need to rerender every pr even if one hasn't made a difference lately.

**Pull request merged**
