### PR TITLE
Add missing dependencies for EUPS

### PR DESCRIPTION
**Pull request by mwittgen**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by timj — APPROVED** [review]
Seems plausible.

**Comment by mwittgen** [comment]
@ktlim Already discussed in PR #29 , I messed up my fork, so the old one was automatically closed.

**Review by ktlim — APPROVED** [review]
OK with me.

**Comment by mwittgen** [comment]
I am lacking write access.

**Pull request merged**
